USE PiedraSportsDB;

DELIMITER $
CREATE PROCEDURE CONSULTA_CARGO () 
BEGIN
	SELECT *
    FROM CARGO;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_EMPLEADO () 
BEGIN
	SELECT *
    FROM EMPLEADO;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_PROVEEDOR() 
BEGIN
	SELECT *
    FROM PROVEEDOR;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_COMPRA() 
BEGIN
	SELECT *
    FROM COMPRA;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_PRODUCTO() 
BEGIN
	SELECT *
    FROM PRODUCTO;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_DETALLE_COMPRA() 
BEGIN
	SELECT *
    FROM DETALLE_COMPRA;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_DETALLE_PRODUCTO() 
BEGIN
	SELECT *
    FROM DETALLE_PRODUCTO;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_CLIENTE() 
BEGIN
	SELECT *
    FROM CLIENTE;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_PEDIDO() 
BEGIN
	SELECT *
    FROM PEDIDO;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_DISTRIBUCION() 
BEGIN
	SELECT *
    FROM DISTRIBUCION;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_VALORACION() 
BEGIN
	SELECT *
    FROM VALORACION;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_VENTA() 
BEGIN
	SELECT *
    FROM VENTA;
END$
DELIMITER $
CREATE PROCEDURE CONSULTA_DETALLE_PEDIDO() 
BEGIN
	SELECT *
    FROM DETALLE_PEDIDO;
END$


