USE PiedraSportsDB;

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CARGO (
IN ID_CARGO INT,
IN NOM_CARGO VARCHAR(50)
)
BEGIN
  UPDATE CARGO
  SET ID_CARGO = ID_CARGO,NOM_CARGO = NOM_CARGO
WHERE ID_CARGO=ID_CARGO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_EMPLEADO (
IN ID_EMPLEADO INTEGER,
IN FECHA_INGRESO_EMPLEADO DATETIME ,
IN NOM_EMPLEADO VARCHAR(100),
IN EMAIL_EMPLEADO VARCHAR(100),
IN MOVIL_EMPLEADO VARCHAR(20),
IN DRR_EMPLEADO VARCHAR(150),
IN ID_CARGO_FK_EMPLEADO INT
)
BEGIN
  UPDATE EMPLEADO
  SET ID_EMPLEADO = ID_EMPLEADO,FECHA_INGRESO_EMPLEADO = FECHA_INGRESO_EMPLEADO,NOM_EMPLEADO = NOM_EMPLEADO, EMAIL_EMPLEADO = EMAIL_EMPLEADO,MOVIL_EMPLEADO = MOVIL_EMPLEADO,DRR_EMPLEADO = DRR_EMPLEADO,ID_CARGO_FK_EMPLEADO = ID_CARGO_FK_EMPLEADO
WHERE ID_EMPLEADO=ID_EMPLEADO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PROVEEDOR (
IN ID_PROVEEDOR INT ,
IN NOM_PROVEEDOR VARCHAR(50),
IN EMAIL_PROVEEDOR VARCHAR(100),
IN MOVIL_PROVEEDOR VARCHAR(20)
)
BEGIN
  UPDATE EMPLEADO
  SET ID_PROVEEDOR = ID_PROVEEDOR,NOM_PROVEEDOR=NOM_PROVEEDOR, EMAIL_PROVEEDOR=EMAIL_PROVEEDOR,MOVIL_PROVEEDOR=MOVIL_PROVEEDOR
WHERE ID_PROVEEDOR=ID_PROVEEDOR;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_COMPRA(
IN ID_COMPRA INT,
IN PRECIO_COMPRA FLOAT,
IN FECHA_COMPRA DATETIME,
IN FORMA_PAGO_COMPRA VARCHAR(50),
IN ID_PROVEEDOR_FK_COMPRA INTEGER
)
BEGIN
	UPDATE COMPRA
    SET ID_COMPRA=ID_COMPRA,PRECIO_COMPRA=PRECIO_COMPRA,FECHA_COMPRA=FECHA_COMPRA,FORMA_PAGO_COMPRA=FORMA_PAGO_COMPRA,ID_PROVEEDOR_FK_COMPRA=ID_PROVEEDOR_FK_COMPRA
WHERE ID_COMPRA=ID_COMPRA;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PRODUCTO(
IN ID_PRODUCTO INT,
IN NOM_PRODUCTO VARCHAR(50),
IN PRECIO_PRODUCTO FLOAT,
IN DESCR_PRODUCTO VARCHAR(200)
)
BEGIN
	UPDATE PRODUCTO
    SET ID_PRODUCTO=ID_PRODUCTO,NOM_PRODUCTO=NOM_PRODUCTO,PRECIO_PRODUCTO=PRECIO_PRODUCTO,DESCR_PRODUCTO=DESCR_PRODUCTO
    WHERE ID_PRODUCTO=ID_PRODUCTO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_COMPRA(
IN ID_PRODUCTO_FK_DETALLE_COMPRA INT,
IN ID_COMPRA_FK_DETALLE_COMPRA INT,
IN DESCRIPCION_DETALLE_COMPRA VARCHAR(250)
)
BEGIN
	UPDATE DETALLE_COMPRA
    SET ID_PRODUCTO_FK_DETALLE_COMPRA=ID_PRODUCTO_FK_DETALLE_COMPRA,ID_COMPRA_FK_DETALLE_COMPRA=ID_COMPRA_FK_DETALLE_COMPRA,DESCRIPCION_DETALLE_COMPRA=DESCRIPCION_DETALLE_COMPRA
    WHERE ID_PRODUCTO_FK_DETALLE_COMPRA=ID_PRODUCTO_FK_DETALLE_COMPRA AND ID_COMPRA_FK_DETALLE_COMPRA=ID_COMPRA_FK_DETALLE_COMPRA;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PRODUCTO(
IN ID_PRODUCTO_FK_DETALLE_PRODUCTO INT,
IN ID_EMPLEADO_FK_DETALLE_PRODUCTO INT,
IN MARCA_PRODUCTO VARCHAR(50),
IN DESC_PRODUCTO_DETALLE_PRODUCTO VARCHAR(150),
IN DESC_DETALLE_PRODUCTO VARCHAR(150)
)
BEGIN
	UPDATE DETALLE_PRODUCTO
    SET ID_PRODUCTO_FK_DETALLE_PRODUCTO=ID_PRODUCTO_FK_DETALLE_PRODUCTO,ID_EMPLEADO_FK_DETALLE_PRODUCTO=ID_EMPLEADO_FK_DETALLE_PRODUCTO,MARCA_PRODUCTO=MARCA_PRODUCTO,DESC_PRODUCTO_DETALLE_PRODUCTO=DESC_PRODUCTO_DETALLE_PRODUCTO
    WHERE ID_PRODUCTO_FK_DETALLE_PRODUCTO=ID_PRODUCTO_FK_DETALLE_PRODUCTO AND ID_EMPLEADO_FK_DETALLE_PRODUCTO=ID_EMPLEADO_FK_DETALLE_PRODUCTO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CLIENTE(
IN ID_CLIENTE INTEGER,
IN NOM_CLIENTE VARCHAR(50),
IN APELL_CLIENTE VARCHAR(50),
IN DRR_CLIENTE VARCHAR(150),
IN EMAIL_CLIENTE VARCHAR(100)
)
BEGIN
	UPDATE CLIENTE
    SET ID_CLIENTE=ID_CLIENTE,NOM_CLIENTE=NOM_CLIENTE,APELL_CLIENTE=APELL_CLIENTE,DRR_CLIENTE=DRR_CLIENTE,EMAIL_CLIENTE=EMAIL_CLIENTE
    WHERE ID_CLIENTE=ID_CLIENTE;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PEDIDO(
IN ID_PEDIDO INT,
IN DESC_PEDIDO VARCHAR(200),
IN FECH_PEDIDO DATETIME,
IN ID_CLIENTE_FK_PEDIDO INT 
)
BEGIN
	UPDATE PEDIDO
    SET ID_PEDIDO=ID_PEDIDO,DESC_PEDIDO=DESC_PEDIDO,FECH_PEDIDO=FECH_PEDIDO,ID_CLIENTE_FK_PEDIDO=ID_CLIENTE_FK_PEDIDO
    WHERE ID_PEDIDO=ID_PEDIDO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DISTRIBUCION(
IN ID_DISTRIBUCION INT,
IN FECHA_INI_DISTRIBUCION DATETIME,
IN FECHA_FIN_DUSTRIBUCION DATETIME,
IN ID_PEDIDO_FK_DISTRIBUCION INT 
)
BEGIN
	UPDATE DISTRIBUCION
    SET ID_DISTRIBUCION=ID_DISTRIBUCION,FECHA_INI_DISTRIBUCION=FECHA_INI_DISTRIBUCION,FECHA_FIN_DUSTRIBUCION=FECHA_FIN_DUSTRIBUCION,ID_PEDIDO_FK_DISTRIBUCION=ID_PEDIDO_FK_DISTRIBUCION
    WHERE ID_DISTRIBUCION=ID_DISTRIBUCION;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VALORACION(
IN ID_VALORACION INT,
IN NUM_VALORACION DOUBLE,
IN DESC_VALORACION VARCHAR(200),
IN ID_PEDIDO_FK_VALORACION INT 
)
BEGIN
	UPDATE VALORACION
    SET ID_VALORACION=ID_VALORACION,NUM_VALORACION=NUM_VALORACION,DESC_VALORACION=DESC_VALORACION,ID_PEDIDO_FK_VALORACION=ID_PEDIDO_FK_VALORACION
    WHERE ID_VALORACION=ID_VALORACION;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VENTA(
IN ID_VENTA INT,
IN PRECIO_TOTAL_VENTA FLOAT,
IN PRECIO_UNITARIO_VENTA_VENTA FLOAT,
IN CANT_PRODUCTO_VENTA INT,
IN FORMA_PAGO_VENTA VARCHAR(50),
IN FECHA_VENTA DATETIME,
IN ID_PEDIDO_FK_VENTA INT,
IN ID_EMPLEADO_FK_VENTA INT  
)
BEGIN
	UPDATE VENTA
    SET ID_VENTA=ID_VENTA,PRECIO_TOTAL_VENTA=PRECIO_TOTAL_VENTA,PRECIO_UNITARIO_VENTA_VENTA=PRECIO_UNITARIO_VENTA_VENTA,
    CANT_PRODUCTO_VENTA=CANT_PRODUCTO_VENTA,FORMA_PAGO_VENTA=FORMA_PAGO_VENTA,FECHA_VENTA=FECHA_VENTA,ID_PEDIDO_FK_VENTA=ID_PEDIDO_FK_VENTA,ID_EMPLEADO_FK_VENTA=ID_EMPLEADO_FK_VENTA
    WHERE ID_VENTA=ID_VENTA;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PEDIDO(
IN ID_PEDIDO_FK_DETALLE_PEDIDO INT,
IN ID_PRODUCTO_FK_DETALLE_PEDIDO INT,
IN DESC_PEDIDO VARCHAR(200)
)
BEGIN
	UPDATE DETALLE_PEDIDO
    SET DETALLE_PEDIDO=DETALLE_PEDIDO,ID_PRODUCTO_FK_DETALLE_PEDIDO=ID_PRODUCTO_FK_DETALLE_PEDIDO,DESC_PEDIDO=DESC_PEDIDO
    WHERE ID_PEDIDO_FK_DETALLE_PEDIDO=ID_PEDIDO_FK_DETALLE_PEDIDO AND ID_PRODUCTO_FK_DETALLE_PEDIDO=ID_PRODUCTO_FK_DETALLE_PEDIDO;
END $