USE PiedraSportsDB;

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_ROL (
IN ID_RO INT,
IN NOM_RO VARCHAR (50))
BEGIN
  UPDATE ROL
  SET  ID_ROL=ID_RO, NOM_ROL=NOM_RO
WHERE  ID_ROL=ID_RO;
END $

CALL ACTUALIZAR_ROL (1,'vendedor');

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_EMPLEADO (
IN ID_EMPLEA INTEGER,
IN FECHA_INGRESO_EMPLEA DATETIME ,
IN NOM_EMPLEA VARCHAR(100),
IN EMAIL_EMPLEA VARCHAR(100),
IN MOVIL_EMPLEA VARCHAR(20),
IN DRR_EMPLEA VARCHAR(150),
IN CONTRASE_EMPLEA VARCHAR (20),
IN ID_ROL_FK_EMPLEA INT)
BEGIN
  UPDATE EMPLEADO
  SET ID_EMPLEADO = ID_EMPLEA,FECHA_INGRESO_EMPLEADO = FECHA_INGRESO_EMPLEA,NOM_EMPLEADO = NOM_EMPLEA, EMAIL_EMPLEADO = EMAIL_EMPLEA,MOVIL_EMPLEADO = MOVIL_EMPLEA,DRR_EMPLEADO = DRR_EMPLEA,CONTRASE_EMPLEADO=CONTRASE_EMPLEA,ID_ROL_FK_EMPLEADO = ID_ROL_FK_EMPLEA
WHERE ID_EMPLEADO = ID_EMPLEA;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PROVEEDOR (
IN ID_PROVEED INT ,
IN NOM_PROVEED VARCHAR(50),
IN EMAIL_PROVEED VARCHAR(100),
IN MOVIL_PROVEED VARCHAR(20))
BEGIN
  UPDATE EMPLEADO
  SET ID_PROVEEDOR = ID_PROVEED,NOM_PROVEEDOR=NOM_PROVEED, EMAIL_PROVEEDOR=EMAIL_PROVEED,MOVIL_PROVEEDOR=MOVIL_PROVEED
WHERE ID_PROVEEDOR = ID_PROVEED;
END $


DELIMITER $
CREATE PROCEDURE ACTUALIZAR_COMPRA(
IN ID_COMP INT,
IN PRECIO_COMP FLOAT,
IN FECHA_COMP DATETIME,
IN FORMA_PAGO_COMP VARCHAR(50),
IN ID_PROVEEDOR_FK_COMP INTEGER)
BEGIN
	UPDATE COMPRA
    SET ID_COMPRA=ID_COMP,PRECIO_COMPRA=PRECIO_COMP,FECHA_COMPRA=FECHA_COMP,FORMA_PAGO_COMPRA=FORMA_PAGO_COMP,ID_PROVEEDOR_FK_COMPRA=ID_PROVEEDOR_FK_COMP
WHERE ID_COMPRA=ID_COMP;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PRODUCTO(
IN ID_PRODUCT INT,
IN NOM_PRODUCT VARCHAR(50),
IN PRECIO_PRODUCT FLOAT,
IN DESCR_PRODUCT VARCHAR(200))
BEGIN
	UPDATE PRODUCTO
    SET ID_PRODUCTO=ID_PRODUCT,NOM_PRODUCTO=NOM_PRODUCT,PRECIO_PRODUCTO=PRECIO_PRODUCT,DESCR_PRODUCTO=DESCR_PRODUCT
    WHERE ID_PRODUCTO=ID_PRODUCT;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_COMPRA(
IN ID_PRODUCTO_FK_DETALLE_COMP INT,
IN ID_COMPRA_FK_DETALLE_COMP INT,
IN DESCRIPCION_DETALLE_COMP VARCHAR(250))
BEGIN
	UPDATE DETALLE_COMPRA
    SET ID_PRODUCTO_FK_DETALLE_COMPRA=ID_PRODUCTO_FK_DETALLE_COMP,ID_COMPRA_FK_DETALLE_COMPRA=ID_COMPRA_FK_DETALLE_COMP,DESCRIPCION_DETALLE_COMPRA=DESCRIPCION_DETALLE_COMP
    WHERE ID_PRODUCTO_FK_DETALLE_COMPRA=ID_PRODUCTO_FK_DETALLE_COMP AND ID_COMPRA_FK_DETALLE_COMPRA=ID_COMPRA_FK_DETALLE_COMP;
END $


DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PRODUCTO(
IN ID_PRODUCTO_FK_DETALLE_PRODUCT INT,
IN ID_EMPLEADO_FK_DETALLE_PRODUCT INT,
IN MARCA_PRODUCT VARCHAR(50),
IN DESC_PRODUCTO_DETALLE_PRODUCT VARCHAR(150),
IN DESC_DETALLE_PRODUCT VARCHAR(150))
BEGIN
	UPDATE DETALLE_PRODUCTO
    SET ID_PRODUCTO_FK_DETALLE_PRODUCTO=ID_PRODUCTO_FK_DETALLE_PRODUCT,ID_EMPLEADO_FK_DETALLE_PRODUCTO=ID_EMPLEADO_FK_DETALLE_PRODUCT,MARCA_PRODUCTO=MARCA_PRODUCT,DESC_PRODUCTO_DETALLE_PRODUCTO=DESC_PRODUCTO_DETALLE_PRODUCT,DESC_DETALLE_PRODUCTO=DESC_DETALLE_PRODUCT
    WHERE ID_PRODUCTO_FK_DETALLE_PRODUCTO=ID_PRODUCTO_FK_DETALLE_PRODUCT AND ID_EMPLEADO_FK_DETALLE_PRODUCTO=ID_EMPLEADO_FK_DETALLE_PRODUCT;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CLIENTE(
IN ID_CLIENT INTEGER,
IN NOM_CLIENT VARCHAR(50),
IN APELL_CLIENT VARCHAR(50),
IN DRR_CLIENT VARCHAR(150),
IN EMAIL_CLIENT VARCHAR(100),
IN CONTRASE_CLIENT VARCHAR (20),
IN ID_ROL_FK_CLIENT INT)
BEGIN
	UPDATE CLIENTE
    SET ID_CLIENTE=ID_CLIENT,NOM_CLIENTE=NOM_CLIENT,APELL_CLIENTE=APELL_CLIENT,DRR_CLIENTE=DRR_CLIENT,EMAIL_CLIENTE=EMAIL_CLIENT,CONTRASE_CLIENTE=CONTRASE_CLIENT,ID_ROL_FK_CLIENTE=ID_ROL_FK_CLIENT
    WHERE ID_CLIENTE=ID_CLIENT;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PEDIDO(
IN ID_PEDID INT,
IN DESC_PEDID VARCHAR(200),
IN FECH_PEDID DATETIME,
IN ID_CLIENTE_FK_PEDID INT)
BEGIN
	UPDATE PEDIDO
    SET ID_PEDIDO=ID_PEDID,DESC_PEDIDO=DESC_PEDID,FECH_PEDIDO=FECH_PEDID,ID_CLIENTE_FK_PEDIDO=ID_CLIENTE_FK_PEDID
    WHERE ID_PEDIDO=ID_PEDID;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DISTRIBUCION(
IN ID_DISTRIBUCIO INT,
IN FECHA_INI_DISTRIBUCIO DATETIME,
IN FECHA_FIN_DUSTRIBUCIO DATETIME,
IN ID_PEDIDO_FK_DISTRIBUCIO INT )
BEGIN
	UPDATE DISTRIBUCION
    SET ID_DISTRIBUCION=ID_DISTRIBUCIO,FECHA_INI_DISTRIBUCION=FECHA_INI_DISTRIBUCIO,FECHA_FIN_DUSTRIBUCION=FECHA_FIN_DUSTRIBUCIO,ID_PEDIDO_FK_DISTRIBUCION=ID_PEDIDO_FK_DISTRIBUCIO
    WHERE ID_DISTRIBUCION=ID_DISTRIBUCIO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VALORACION(
IN ID_VALORACIO INT,
IN NUM_VALORACIO DOUBLE,
IN DESC_VALORACIO VARCHAR(200),
IN ID_PEDIDO_FK_VALORACIO INT )
BEGIN
	UPDATE VALORACION
    SET ID_VALORACION=ID_VALORACIO,NUM_VALORACION=NUM_VALORACIO,DESC_VALORACION=DESC_VALORACIO,ID_PEDIDO_FK_VALORACION=ID_PEDIDO_FK_VALORACIO
    WHERE ID_VALORACION=ID_VALORACIO;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VENTA(
IN ID_VENT INT,
IN PRECIO_TOTAL_VENT FLOAT,
IN PRECIO_UNITARIO_VENTA_VENT FLOAT,
IN CANT_PRODUCTO_VENT INT,
IN FORMA_PAGO_VENT VARCHAR(50),
IN FECHA_VENT DATETIME,
IN ID_PEDIDO_FK_VENT INT,
IN ID_EMPLEADO_FK_VENT INT)
BEGIN
	UPDATE VENTA
    SET ID_VENTA=ID_VENT,PRECIO_TOTAL_VENTA=PRECIO_TOTAL_VENT,PRECIO_UNITARIO_VENTA_VENTA=PRECIO_UNITARIO_VENTA_VENT,
    CANT_PRODUCTO_VENTA=CANT_PRODUCTO_VENT,FORMA_PAGO_VENTA=FORMA_PAGO_VENT,FECHA_VENTA=FECHA_VENT,ID_PEDIDO_FK_VENTA=ID_PEDIDO_FK_VENT,ID_EMPLEADO_FK_VENTA=ID_EMPLEADO_FK_VENT
    WHERE ID_VENTA=ID_VENT;
END $

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PEDIDO(
IN ID_PEDIDO_FK_DETALLE_PEDID INT,
IN ID_PRODUCTO_FK_DETALLE_PEDID INT,
IN DESC_PEDID VARCHAR(200))
BEGIN
	UPDATE DETALLE_PEDIDO
    SET ID_PEDIDO_FK_DETALLE_PEDIDO=ID_PEDIDO_FK_DETALLE_PEDID,ID_PRODUCTO_FK_DETALLE_PEDIDO=ID_PRODUCTO_FK_DETALLE_PEDID,DESC_PEDIDO=DESC_PEDID
    WHERE ID_PEDIDO_FK_DETALLE_PEDIDO=ID_PEDIDO_FK_DETALLE_PEDID AND ID_PRODUCTO_FK_DETALLE_PEDIDO=ID_PRODUCTO_FK_DETALLE_PEDID;
END $