USE PiedraSportsDB;

DELIMITER $
CREATE PROCEDURE ELIMINAR_ROL (IN IDROL INT)
BEGIN 
	DELETE FROM ROL
    WHERE ID_ROL=IDROL;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_EMPLEADO(IN IDEMPLEADO INTEGER)
BEGIN 
	DELETE FROM EMPLEADO
    WHERE ID_EMPLEADO=IDEMPLEADO;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_PROVEEDOR(IN IDPROVEEDOR INT)
BEGIN 
	DELETE FROM PROVEEDOR
    WHERE ID_PROVEEDOR=IDPROVEEDOR;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_COMPRA(IN IDCOMPRA INT)
BEGIN 
	DELETE FROM COMPRA
    WHERE ID_COMPRA=IDCOMPRA;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_PRODUCTO(IN IDPRODUCTO INT)
BEGIN 
	DELETE FROM PRODUCTO
    WHERE ID_PRODUCTO=IDPRODUCTO;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_COMPRA(IN IDPRODUCTOFKDETALLECOMPRA INT)
BEGIN 
	DELETE FROM DETALLE_COMPRA
    WHERE ID_PRODUCTO_FK_DETALLE_COMPRA=IDPRODUCTOFKDETALLECOMPRA;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_PRODUCTO(IN IDPRODUCTOFKDETALLEPRODUCTO INT)
BEGIN 
	DELETE FROM DETALLE_PRODUCTO
    WHERE ID_PRODUCTO_FK_DETALLE_PRODUCTO=IDPRODUCTOFKDETALLEPRODUCTO;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_CLIENTE(IN IDCLIENTE INTEGER)
BEGIN 
	DELETE FROM CLIENTE
    WHERE ID_CLIENTE=IDCLIENTE;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_PEDIDO(IN IDPEDIDO INT)
BEGIN 
	DELETE FROM PEDIDO
    WHERE ID_PEDIDO=IDPEDIDO;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_DISTRIBUCION(IN IDDISTRIBUCION INT)
BEGIN 
	DELETE FROM DISTRIBUCION
    WHERE ID_DISTRIBUCION=IDDISTRIBUCION;
END $
 
DELIMITER $
CREATE PROCEDURE ELIMINAR_VALORACION(IN IDVALORACION INT)
BEGIN 
	DELETE FROM VALORACION
    WHERE ID_VALORACION=IDVALORACION;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_VENTA(IN IDVENTA INT)
BEGIN 
	DELETE FROM VENTA
    WHERE ID_VENTA=IDVENTA;
END $ 

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_PEDIDO(IN IDPEDIDOFKDETALLEPEDIDO INT)
BEGIN 
	DELETE FROM DETALLE_PEDIDO
    WHERE ID_PEDIDO_FK_DETALLE_PEDIDO=IDPEDIDOFKDETALLEPEDIDO;
END $ 