USE PiedraSportsDB;

SELECT *FROM ROL

DELIMITER $
CREATE PROCEDURE INSERTAR_ROL (IN ID_ROL INT,IN NOM_ROL VARCHAR (50))
BEGIN
INSERT INTO ROL (ID_ROL,NOM_ROL)
VALUES (ID_ROL,NOM_ROL);
END$

INSERT INTO ROL VALUES (NULL,"administrador")

DELIMITER $
CREATE PROCEDURE INSERTAR_EMPLEADO (IN ID_EMPLE INTEGER,IN FECHA_INGRESO_EMPLE DATETIME,
IN NOM_EMPLE VARCHAR(100),IN EMAIL_EMPLE VARCHAR(100),IN MOVIL_EMPLE VARCHAR(20),
IN DRR_EMPLE VARCHAR(150),IN CONTRASE_EMPLE VARCHAR(20),IN ID_ROL_FK_EMPLE INT)
BEGIN
INSERT INTO EMPLEADO (ID_EMPLEADO,FECHA_INGRESO_EMPLEADO,NOM_EMPLEADO,EMAIL_EMPLEADO,MOVIL_EMPLEADO,DRR_EMPLEADO,CONTRASE_EMPLEADO,ID_ROL_FK_EMPLEADO)
VALUES (ID_EMPLE,FECHA_INGRESO_EMPLE,NOM_EMPLE,EMAIL_EMPLE,MOVIL_EMPLE,DRR_EMPLE,CONTRASE_EMPLE,ID_ROL_FK_EMPLE);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PROVEEDOR (IN ID_PROVEE INT,IN NOM_PROVEE VARCHAR(50),
IN EMAIL_PROVEE VARCHAR(100),IN MOVIL_PROVEEDOR VARCHAR(20))
BEGIN
INSERT INTO PROVEEDOR (ID_PROVEEDOR,NOM_PROVEEDOR,EMAIL_PROVEEDOR,MOVIL_PROVEEDOR)
VALUES (ID_PROVEE,NOM_PROVEE,EMAIL_PROVEE,MOVIL_PROVEEDOR);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_COMPRA (IN ID_COM INT,IN PRECIO_COM FLOAT ,
IN FECHA_COM DATETIME,IN FORMA_PAGO_COM VARCHAR(50),IN ID_PROVEEDOR_FK_COM INTEGER)
BEGIN
INSERT INTO COMPRA (ID_COMPRA,PRECIO_COMPRA,FECHA_COMPRA,FORMA_PAGO_COMPRA,ID_PROVEEDOR_FK_COMPRA)
VALUES (ID_COM,PRECIO_COM,FECHA_COM,FORMA_PAGO_COM,ID_PROVEEDOR_FK_COM);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCTO (IN ID_PRODUC INT,IN NOM_PRODUC VARCHAR(50) ,
IN PRECIO_PRODUC FLOAT,IN DESCR_PRODUC VARCHAR(200))
BEGIN
INSERT INTO PRODUCTO (ID_PRODUCTO,NOM_PRODUCTO,PRECIO_PRODUCTO,DESCR_PRODUCTO)
VALUES (ID_PRODUC,NOM_PRODUC,PRECIO_PRODUC,DESCR_PRODUC);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_COMPRA (IN ID_PRODUCTO_FK_DETALLE_COM INT,
IN ID_COMPRA_FK_DETALLE_COM INT ,IN DESCRIPCION_DETALL VARCHAR(250))
BEGIN
INSERT INTO DETALLE_COMPRA (ID_PRODUCTO_FK_DETALLE_COMPRA,ID_COMPRA_FK_DETALLE_COMPRA,DESCRIPCION_DETALLE)
VALUES (ID_PRODUCTO_FK_DETALLE_COM,ID_COMPRA_FK_DETALLE_COM,DESCRIPCION_DETALL);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PRODUCTO (IN ID_PRODUCTO_FK_DETALLE_PRODUC INT,
IN ID_EMPLEADO_FK_DETALLE_PRODUC INT,IN MARCA_PRODUC VARCHAR(50),IN DESC_PRODUCTO_DETALLE_PRODUC VARCHAR(150),
IN DESC_DETALLE_PRODUC VARCHAR(150))
BEGIN
INSERT INTO DETALLE_PRODUCTO (ID_PRODUCTO_FK_DETALLE_PRODUCTO,ID_EMPLEADO_FK_DETALLE_PRODUCTO,MARCA_PRODUCTO,DESC_PRODUCTO_DETALLE_PRODUCTO,DESC_DETALLE_PRODUCTO)
VALUES (ID_PRODUCTO_FK_DETALLE_PRODUC,ID_EMPLEADO_FK_DETALLE_PRODUC,MARCA_PRODUC,DESC_PRODUCTO_DETALLE_PRODUC,DESC_DETALLE_PRODUC);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_CLIENTE (IN ID_CLIEN INTEGER,IN NOM_CLIEN VARCHAR(50),
IN APELL_CLIEN VARCHAR(50),IN DRR_CLIEN VARCHAR(150),IN EMAIL_CLIEN VARCHAR(100), IN CONTRASE_CLIEN VARCHAR(20),
IN ID_ROL_FK_CLIEN INT)
BEGIN
INSERT INTO CLIENTE (ID_CLIENTE,NOM_CLIENTE,APELL_CLIENTE,DRR_CLIENTE,EMAIL_CLIENTE,CONTRASE_CLIENTE,ID_ROL_FK_CLIENTE)
VALUES (ID_CLIEN,NOM_CLIEN,APELL_CLIEN,DRR_CLIEN,EMAIL_CLIEN,CONTRASE_CLIEN,ID_ROL_FK_CLIEN);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PEDIDO (IN ID_PEDI INT,IN DESC_PEDI VARCHAR(200),
IN FECH_PEDI DATETIME,IN ID_CLIENTE_FK_PEDI INT)
BEGIN
INSERT INTO PEDIDO (ID_PEDIDO,DESC_PEDIDO,FECH_PEDIDO,ID_CLIENTE_FK_PEDIDO)
VALUES (ID_PEDI,DESC_PEDI,FECH_PEDI,ID_CLIENTE_FK_PEDI);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DISTRIBUCION (IN ID_DISTRIBUCI INT,IN FECHA_INI_DISTRIBUCI DATETIME,
IN FECHA_FIN_DUSTRIBUCI DATETIME,IN ID_PEDIDO_FK_DISTRIBUCI INT)
BEGIN
INSERT INTO DISTRIBUCION (ID_DISTRIBUCION,FECHA_INI_DISTRIBUCION,FECHA_FIN_DUSTRIBUCION,ID_PEDIDO_FK_DISTRIBUCION)
VALUES (ID_DISTRIBUCI,FECHA_INI_DISTRIBUCI,FECHA_FIN_DUSTRIBUCI,ID_PEDIDO_FK_DISTRIBUCI);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_VALORACION (IN ID_VALORACI INT,IN NUM_VALORACI DOUBLE,
IN DESC_VALORACI VARCHAR(200),IN ID_PEDIDO_FK_VALORACI INT)
BEGIN
INSERT INTO VALORACION (ID_VALORACION,NUM_VALORACION,DESC_VALORACION,ID_PEDIDO_FK_VALORACION)
VALUES (ID_VALORACI,NUM_VALORACI,DESC_VALORACI,ID_PEDIDO_FK_VALORACI);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_VENTA (IN ID_VEN INT,IN PRECIO_TOTAL_VEN FLOAT,
IN PRECIO_UNITARIO_VENTA_VEN FLOAT,IN CANT_PRODUCTO_VEN INT,IN FORMA_PAGO_VEN VARCHAR(50),
IN FECHA_VEN DATETIME,IN ID_PEDIDO_FK_VEN INT,IN ID_EMPLEADO_FK_VEN INT)
BEGIN
INSERT INTO VENTA (ID_VENTA,PRECIO_TOTAL_VENTA,PRECIO_UNITARIO_VENTA_VENTA,CANT_PRODUCTO_VENTA,
FORMA_PAGO_VENTA,FECHA_VENTA,ID_PEDIDO_FK_VENTA,ID_EMPLEADO_FK_VENTA)
VALUES (ID_VEN,PRECIO_TOTAL_VEN,PRECIO_UNITARIO_VENTA_VEN,CANT_PRODUCTO_VEN,FORMA_PAGO_VEN,FECHA_VEN,
ID_PEDIDO_FK_VEN,ID_EMPLEADO_FK_VEN);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PEDIDO (IN ID_PEDIDO_FK_DETALLE_PEDI INT,
IN ID_PRODUCTO_FK_DETALLE_PEDI INT ,IN DESC_PEDI VARCHAR(200))
BEGIN
INSERT INTO DETALLE_PEDIDO (ID_PEDIDO_FK_DETALLE_PEDIDO,ID_PRODUCTO_FK_DETALLE_PEDIDO,DESC_PEDIDO)
VALUES (ID_PEDIDO_FK_DETALLE_PEDI,ID_PRODUCTO_FK_DETALLE_PEDI,DESC_PEDI);
END$










