CREATE DATABASE PiedraSportsDB;
USE PiedraSportsDB;

CREATE TABLE CARGO(
ID_CARGO INT PRIMARY KEY AUTO_INCREMENT,
NOM_CARGO VARCHAR(50) NOT NULL
);
CREATE TABLE EMPLEADO(
ID_EMPLEADO INTEGER PRIMARY KEY AUTO_INCREMENT,
FECHA_INGRESO_EMPLEADO DATETIME NOT NULL,
NOM_EMPLEADO VARCHAR(100) NOT NULL,
EMAIL_EMPLEADO VARCHAR(100) NOT NULL,
MOVIL_EMPLEADO VARCHAR(20) NOT NULL,
DRR_EMPLEADO VARCHAR(150) NOT NULL,
ID_CARGO_FK_EMPLEADO INT NOT NULL,
FOREIGN KEY (ID_CARGO_FK_EMPLEADO) REFERENCES CARGO(ID_CARGO)
);
CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOM_PROVEEDOR VARCHAR(50) NOT NULL,
EMAIL_PROVEEDOR VARCHAR(100) NOT NULL,
MOVIL_PROVEEDOR VARCHAR(20) NOT NULL
);
CREATE TABLE COMPRA(
ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
PRECIO_COMPRA FLOAT NOT NULL,
FECHA_COMPRA DATETIME NOT NULL,
FORMA_PAGO_COMPRA VARCHAR(50) NOT NULL,
ID_PROVEEDOR_FK_COMPRA INTEGER NOT NULL,
FOREIGN KEY (ID_PROVEEDOR_FK_COMPRA) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);
CREATE TABLE PRODUCTO(
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
NOM_PRODUCTO VARCHAR(50) NOT NULL,
PRECIO_PRODUCTO FLOAT NOT NULL,
DESCR_PRODUCTO VARCHAR(200) NULL
);
CREATE TABLE DETALLE_COMPRA(
ID_PRODUCTO_FK_DETALLE_COMPRA INT NOT NULL,
FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_COMPRA) REFERENCES PRODUCTO(ID_PRODUCTO),
ID_COMPRA_FK_DETALLE_COMPRA INT NOT NULL,
FOREIGN KEY (ID_COMPRA_FK_DETALLE_COMPRA) REFERENCES COMPRA(ID_COMPRA),
DESCRIPCION_DETALLE_COMPRA VARCHAR(250) NOT NULL
);
CREATE TABLE DETALLE_PRODUCTO(
ID_PRODUCTO_FK_DETALLE_PRODUCTO INT NOT NULL,
FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
ID_EMPLEADO_FK_DETALLE_PRODUCTO INT NOT NULL,
FOREIGN KEY (ID_EMPLEADO_FK_DETALLE_PRODUCTO) REFERENCES EMPLEADO(ID_EMPLEADO),
MARCA_PRODUCTO VARCHAR(50) NOT NULL,
DESC_PRODUCTO_DETALLE_PRODUCTO VARCHAR(150),
DESC_DETALLE_PRODUCTO VARCHAR(150) NOT NULL
);
CREATE TABLE CLIENTE(
ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
NOM_CLIENTE VARCHAR(50) NOT NULL,
APELL_CLIENTE VARCHAR(50) NOT NULL,
DRR_CLIENTE VARCHAR(150) NOT NULL,
EMAIL_CLIENTE VARCHAR(100) NOT NULL
);
CREATE TABLE PEDIDO(
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
DESC_PEDIDO VARCHAR(200) NULL,
FECH_PEDIDO DATETIME NOT NULL,
ID_CLIENTE_FK_PEDIDO INT NOT NULL,
FOREIGN KEY (ID_CLIENTE_FK_PEDIDO ) REFERENCES CLIENTE(ID_CLIENTE)
);
CREATE TABLE DISTRIBUCION(
ID_DISTRIBUCION INT PRIMARY KEY AUTO_INCREMENT,
FECHA_INI_DISTRIBUCION DATETIME NOT NULL,
FECHA_FIN_DUSTRIBUCION DATETIME NOT NULL,
ID_PEDIDO_FK_DISTRIBUCION INT NOT NULL,
FOREIGN KEY (ID_PEDIDO_FK_DISTRIBUCION) REFERENCES PEDIDO(ID_PEDIDO)
);
CREATE TABLE VALORACION(
ID_VALORACION INT PRIMARY KEY AUTO_INCREMENT,
NUM_VALORACION DOUBLE NOT NULL,
DESC_VALORACION VARCHAR(200) NULL,
ID_PEDIDO_FK_VALORACION INT NOT NULL,
FOREIGN KEY (ID_PEDIDO_FK_VALORACION) REFERENCES PEDIDO(ID_PEDIDO)
);
CREATE TABLE VENTA(
ID_VENTA INT PRIMARY KEY NOT NULL,
PRECIO_TOTAL_VENTA FLOAT NOT NULL,
PRECIO_UNITARIO_VENTA_VENTA FLOAT NOT NULL,
CANT_PRODUCTO_VENTA INT NOT NULL,
FORMA_PAGO_VENTA VARCHAR(50) NOT NULL,
FECHA_VENTA DATETIME NOT NULL,
ID_PEDIDO_FK_VENTA INT NOT NULL,
FOREIGN KEY (ID_PEDIDO_FK_VENTA) REFERENCES PEDIDO(ID_PEDIDO),
ID_EMPLEADO_FK_VENTA INT NOT NULL,
FOREIGN KEY (ID_EMPLEADO_FK_VENTA) REFERENCES EMPLEADO(ID_EMPLEADO)
);
CREATE TABLE DETALLE_PEDIDO(
ID_PEDIDO_FK_DETALLE_PEDIDO INT NOT NULL,
FOREIGN KEY (ID_PEDIDO_FK_DETALLE_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
ID_PRODUCTO_FK_DETALLE_PEDIDO INT NOT NULL,
FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_PEDIDO) REFERENCES PRODUCTO(ID_PRODUCTO),
DESC_PEDIDO VARCHAR(200) NOT NULL
)